Spring:
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  datasource:
    url: jdbc:h2:tcp://localhost/~/medium
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
 #       show-sql: true
        format_sql: true

logging:
 level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩

medium:
  jwt-key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey